### ISSUE TITLE
Determine Back-End

### ISSUE THREAD

**Issue by JaynewDee** [akelstrom/grocery-tracker#4]
- Leave a comment here to vote for your preferred back-end technologies.

**Comment by JaynewDee** [comment]
_**React/Next.js**_

**Comment by akelstrom** [comment]
Next.js (instead of express)
Mongo DB/Mongoose (database)

**Comment by sarahwylie** [comment]
I'm down with whatever - I have experience in Express, SQL/Sequelize, Mongo/Mongoose, Node. It was cool to hear how exciting Nest might be - didn't we already determine this last night? Or did we just discuss possibilities?

**Comment by JaynewDee** [comment]
> I'm down with whatever - I have experience in Express, SQL/Sequelize, Mongo/Mongoose, Node. It was cool to hear how exciting Nest might be - didn't we already determine this last night? Or did we just discuss possibilities?

Given a quick exchange with Alex and what you've shared here, I imagine we'll be going with Nest. According to the docs, it's built such that it works right on top of Express, so it should be conceptually quite similar!  Some of the syntax is unfamiliar to me personally but I'm excited to learn it

**Comment by JaynewDee** [comment]
> Nest.js (instead of express)
> 
> Node.js- typescript??- (typescript is basically javascript but with additional features- which means we could write in javascript but still use typescript  features if we have it installed)
> 
> Mongoose for ORM if we use MongoDB, Sequelize for SQL if we go that route

I'm totally down for TypeScript. Like you mentioned, if we allow js within the tsconfig, we can utilize typescript optionally or incrementally
