### ISSUE TITLE
Determine Database

### ISSUE THREAD

**Issue by JaynewDee** [akelstrom/grocery-tracker#5]
- Leave a comment here to vote for your preferred database technology.

**Comment by JaynewDee** [comment]
Example:

**_MongoDB_**

**Comment by akelstrom** [comment]
MongoDB/mongoose

**Comment by akelstrom** [comment]
setting up PostgreSQL on a mac: https://www.sqlshack.com/setting-up-a-postgresql-database-on-mac/
prerequisites: homebrew
